name: Static Analysis

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
